# Generated by Django 4.1.4 on 2023-01-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('timezone', models.CharField(max_length=50)),
                ('average_cost_kwh', models.FloatField()),
                ('unit_cost', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_sub_site', models.BooleanField()),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('efficiency_index', models.FloatField(blank=True, null=True)),
                ('size_mq', models.IntegerField()),
                ('size_mc', models.IntegerField()),
                ('max_power_w', models.IntegerField()),
                ('max_power_over_time', models.CharField(blank=True, max_length=50)),
                ('max_daily_energy_wh', models.IntegerField()),
                ('target_daily_generation_w', models.IntegerField()),
                ('max_power_generation_w', models.IntegerField()),
                ('contract_power_w', models.IntegerField(blank=True, null=True)),
                ('target_daily_fedout_wh', models.IntegerField()),
                ('max_daily_fedin_wh', models.IntegerField()),
                ('max_daily_self_consumption_wh', models.IntegerField()),
                ('target_power_fedout_w', models.IntegerField()),
                ('max_power_fedin_w', models.IntegerField()),
                ('max_power_self_consumption_w', models.IntegerField()),
                ('stake_id', models.CharField(blank=True, max_length=50)),
                ('etag', models.IntegerField()),
                ('_id', models.CharField(max_length=50)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
    ]
